#!/bin/sh

# Define the directory containing the video files
VIDEO_DIR="/home/psoldunov/Videos/Wallpapers"

# Check if mpvpaper is running and kill it
if pgrep -x "mpvpaper" > /dev/null
then
    echo "mpvpaper is running. Stopping it now..."
    pkill -x "mpvpaper"
fi

# Wait a bit to ensure mpvpaper has stopped
sleep 1

# Get a random video file from the directory
RANDOM_VIDEO=$(find "$VIDEO_DIR" -type f \( -name "*.mp4" -o -name "*.mkv" \) | shuf -n 1)
VIDEO_PATH=$RANDOM_VIDEO

# Launch mpvpaper with the random video
mpvpaper -o "loop" '*' "$VIDEO_PATH" &

ffmpeg -y -i "$VIDEO_PATH" -vframes 1 "/tmp/lock_background.png"
convert "/tmp/lock_background.png" -blur 0x10 "/usr/share/backgrounds/user/lock_background.png"
exit 0
