#!/usr/bin/env bash

threshhold_green=0
threshhold_yellow=25
threshhold_red=100

# ----------------------------------------------------- 
# Calculate available updates: dnf, flatpak, and homebrew
# ----------------------------------------------------- 

updates_dnf=$(dnf check-update --quiet | grep -vc '^$')
updates_flatpak=$(flatpak remote-ls --updates | wc -l)

# Check if Homebrew is installed before trying to check for updates
if type brew &> /dev/null; then
    updates_brew=$(brew outdated | wc -l)
else
    updates_brew=0
fi

updates=$((updates_dnf + updates_flatpak + updates_brew))

# ----------------------------------------------------- 
# Output in JSON format for Waybar Module custom-updates
# ----------------------------------------------------- 

css_class="green"

if [ "$updates" -gt "$threshhold_yellow" ]; then
    css_class="yellow"
fi

if [ "$updates" -gt "$threshhold_red" ]; then
    css_class="red"
fi

if [ "$updates" -gt "$threshhold_green" ]; then
    printf '{"text": "%s", "alt": "%s", "tooltip": "%s Updates", "class": "%s"}\n' "$updates" "$updates" "$updates" "$css_class"
else
    printf '{"text": "0", "alt": "0", "tooltip": "0 Updates", "class": "green"}\n'
fi
